apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: football-manager
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "CHANGE_ME"
  MONGO_URI: "mongodb://admin:CHANGE_ME@mongodb-service:27017"
