apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: football-manager
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "CHANGE_ME"
  RABBITMQ_URL: "amqp://admin:CHANGE_ME@rabbitmq-service:5672"
