apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: football-manager
data:
  PORT: "3001"
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb-service:27017"
  MONGO_DATABASE: "football_manager"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  REDIS_URL: "redis://redis-service:6379"
  CLUB_SERVICE_URL: "http://club-service:3002"
  PLAYER_SERVICE_URL: "http://player-service:3003"
  MATCH_SERVICE_URL: "http://match-service:3004"
  ECONOMY_SERVICE_URL: "http://economy-service:3005"
  YOUTH_SERVICE_URL: "http://youth-service:3006"
  LEAGUE_SERVICE_URL: "http://league-service:3007"
  MESSAGE_SERVICE_URL: "http://message-service:3008"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3009"
