apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: football-manager
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://api-gateway-service:3001"
  NEXT_PUBLIC_WS_URL: "ws://api-gateway-service:3001"
