apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: football-manager

resources:
  - namespace.yaml
  - pv-pvc.yaml

components:
  - configmaps/
  - secrets/
  - services/
  - deployments/
  - hpa/
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: football-manager
  app.kubernetes.io/part-of: football-manager
